
# Loads default set of integrations. Do not remove.
default_config:

binary_sensor:
  - platform: hikvision
    host: 10.0.0.128
    port: 80
    ssl: false
    username: !secret hikvision_username
    password: !secret hikvision_password

lutron_caseta:
  - host: 10.0.0.57
    keyfile: lutron_caseta-10.0.0.57-key.pem
    certfile: lutron_caseta-10.0.0.57-cert.pem
    ca_certs: lutron_caseta-10.0.0.57-ca.pem

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
