name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.7.15

      - name: Setup environment
        run: |
          mv travis_secrets.yaml secrets.yaml
          sudo apt-get update
          sudo apt-get install -y libudev-dev
      
      - name: Install Home Assistant
        run: pip3 install homeassistant

      - name: Run test
        run: hass -c . --script check_config
